In [18]:
import tqdm
import yfinance as yf
import pandas as pd

In [15]:
# Load D:\financial-data\marketsmith\all\2024-08-16.parquet
df = pd.read_parquet('D:/financial-data/marketsmith/all/2024-08-16.parquet')
df = df[df['Current Price'] > 1]
df

,MSID,isGlobal,Symbol,Name,EPS Rating,RS Rating,SMR Rating,A/D Rating,Comp Rating,EPS % Chg Last Qtr,...,RS Rating RS Rating,RS Rating 1 Week Ago,RS Rating 4 Weeks Ago,RS Rating 3 Months Ago,RS Rating 6 Months Ago,RS Rating 1 Year Ago,RS Rating RS 3-Month,RS Rating RS 6-Month,RS Rating 52 Week High,RS Line Blue Dot Event Date WD
0,3822,False,A,Agilent Technologies,73,55,B,B,68,-4,...,None,None,None,None,None,None,None,None,None,(w)
1,15144360,False,AA,Alcoa,33,43,E,D-,28,<NA>,...,None,None,None,None,None,None,None,None,None,(w)
2,21927543,False,AAA,Alt Access First Priority,0,35,NaN,D+,<NA>,1,...,None,None,None,None,None,None,None,None,None,None
3,18404033,False,AAAU,Goldman Sachs Phys Gold,0,83,NaN,D,<NA>,22,...,None,None,None,None,None,None,None,None,None,None
5,32129318,False,AACI,Armada Acquisition I,3,20,NaN,B+,15,<NA>,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10161,40553206,False,ZVSA,ZyVersa Therapeutics,57,2,NaN,D-,25,<NA>,...,None,None,None,None,None,None,None,None,None,None
10162,6848384,False,ZWS,Zurn Elkay Water Solns,79,33,B,C,65,38,...,None,None,None,None,None,None,None,None,None,(w)
10163,15934327,False,ZYME,Zymeworks,24,85,D,C-,65,<NA>,...,None,None,None,None,None,None,None,None,None,None
10164,6712,False,ZYXI,Zynex,27,12,B,D,28,-56,...,None,None,None,None,None,None,None,None,None,"(d,w)"
10165,59975803,False,ZZZ,Cyber Hornet S&P 500,0,63,NaN,D,<NA>,<NA>,...,12,17,33,61,92,11,5,6,0,None

In [21]:
symbols = df['Symbol'].to_list()
# iterate over symbols by 1000
df_yahoos = []
for i in tqdm.trange(0, len(symbols), 1000):
    df_yahoo = yf.download(symbols[i:i+1000])
    df_yahoos.append(df_yahoo)

[************          24%%                      ]  238 of 1000 completed

$BHA: possibly delisted; No price data found  (1d 1925-09-10 -> 2024-08-16)

[*********************100%%**********************]  1000 of 1000 completed

11 Failed downloads:
['BIOB', 'AKOB', 'AKOA', 'BFA', 'BGRY', 'AGMA', 'ALOR', 'ARYE', 'BFB']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
['BHA']: YFPricesMissingError('$%ticker%: possibly delisted; No price data found  (1d 1925-09-10 -> 2024-08-16)')
['AVTA']: YFInvalidPeriodError("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")
[**********************47%%                      ]  473 of 1000 completed

$CRDA: possibly delisted; No price data found  (1d 1925-09-10 -> 2024-08-16)

[**********************73%%*********             ]  726 of 1000 completed

$CRDB: possibly delisted; No price data found  (1d 1925-09-10 -> 2024-08-16)

[*********************100%%**********************]  1000 of 1000 completed

16 Failed downloads:
['CTG', 'BRD', 'CCVI', 'CD']: YFChartError('%ticker%: No data found, symbol may be delisted')
['BRKB', 'CHRA', 'CORS', 'BLU', 'BRIV', 'BLNG', 'CWENA', 'CTIC', 'BRKA']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
['CNCE']: YFInvalidPeriodError("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")
['CRDA', 'CRDB']: YFPricesMissingError('$%ticker%: possibly delisted; No price data found  (1d 1925-09-10 -> 2024-08-16)')
[*********************100%%**********************]  1000 of 1000 completed

11 Failed downloads:
['DCPH', 'EDI', 'DISA', 'DISH', 'FATP']: YFChartError('%ticker%: No data found, symbol may be delisted')
['ENTF', 'EBRB', 'DNAB', 'EOCW', 'DSEY', 'DNAD']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
[*********************100%%**********************]  1000 of 1000 completed

12 Failed downloads:
['HMA', 'FMIV', 'GTNA', 'GER', 'HEIA', 'GEFB']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
['FRXB', 'FIF', 'FEI', 'FPL', 'FEN', 'GDNR']: YFChartError('%ticker%: No data found, symbol may be delisted')
[*********************100%%**********************]  1000 of 1000 completed

11 Failed downloads:
['JPS', 'ISEE', 'HVTA', 'JPT', 'IRL', 'INDT', 'HWKZ']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
['HWEL', 'KVSA', 'IHIT', 'HTY']: YFChartError('%ticker%: No data found, symbol may be delisted')
[*********************100%%**********************]  1000 of 1000 completed

15 Failed downloads:
['LGFB', 'MKCV', 'LGFA', 'LENB', 'NKG', 'MOGA', 'MLVF', 'MOGB', 'NID', 'NIQ', 'MEOA']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
['MBAC', 'LHC', 'LVOX', 'MFV']: YFChartError('%ticker%: No data found, symbol may be delisted')
[*********************100%%**********************]  1000 of 1000 completed

6 Failed downloads:
['NUO', 'PBRA', 'PRBM']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
['PACW', 'PCTI', 'PFIN']: YFChartError('%ticker%: No data found, symbol may be delisted')
[*********************100%%**********************]  1000 of 1000 completed

4 Failed downloads:
['SJR', 'SCAQ', 'SDAC']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
['RACY']: YFChartError('%ticker%: No data found, symbol may be delisted')
[*******               15%%                      ]  149 of 1000 completed

$TAPA: possibly delisted; No price data found  (1d 1925-09-10 -> 2024-08-16)

[*********************100%%**********************]  1000 of 1000 completed

10 Failed downloads:
['TBCP', 'VMW']: YFChartError('%ticker%: No data found, symbol may be delisted')
['TAPA']: YFPricesMissingError('$%ticker%: possibly delisted; No price data found  (1d 1925-09-10 -> 2024-08-16)')
['UHALB', 'TOSYY', 'USX', 'TCFC', 'TESS', 'VBOC', 'TWCB']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
[*********************100%%**********************]  447 of 447 completed

2 Failed downloads:
['WSOB', 'WQGA']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
100%|██████████| 10/10 [05:07<00:00, 30.78s/it]